### ISSUE TITLE
Is there any way to wrap text or expand the code editor?

### ISSUE THREAD

**Issue by batmanscode** [samdobson/streamlit-sandbox#5]
![image](https://user-images.githubusercontent.com/29989939/152301922-a4e3366a-c825-41cd-a38b-eb1558199ffc.png)

**Comment by samdobson** [comment]
Thanks for reporting. With the latest update, the editor is now full-screen.

**Comment by samdobson** [comment]
Also if you need, text wrapping can be enabled by checking the relevant box in the sidebar.

**Comment by batmanscode** [comment]
Thanks for getting to it, great work @samdobson!
