### ISSUE TITLE
Can't insert st.columns inside column

### ISSUE THREAD

**Issue by Rchatru** [samdobson/streamlit-sandbox#6]
This application idea is very good for quick testing, but I am encountering a problem when I want to insert a column.

![example](https://user-images.githubusercontent.com/38190230/207145866-bdba03bc-3e69-4393-8b1f-278e6aefd8f2.PNG)

![error](https://user-images.githubusercontent.com/38190230/207145761-c672672e-ee0e-4065-b5de-7de69505bf42.PNG)

As indicated in the error message, and in the st.columns documentation, you should not insert a column inside another one. But in this case, due to the structure of the application (two columns) it is not possible to insert another one.

Would it be possible to make any change in the application structure to allow the user to insert columns?

**Comment by samdobson** [comment]
Thanks for reporting. With the latest Streamlit update, this is now fixed.

<img width="1305" alt="nested-columns" src="https://user-images.githubusercontent.com/1309834/221358960-a614f4a0-7557-40ec-be28-a098d81f4e90.png">

**Comment by Rchatru** [comment]
Awesome, thanks!
